-- DropForeignKey
ALTER TABLE "TB_ROLE_MODULE" DROP CONSTRAINT "TB_ROLE_MODULE_moduleId_fkey";

-- AddForeignKey
ALTER TABLE "TB_ROLE_MODULE" ADD CONSTRAINT "TB_ROLE_MODULE_moduleId_fkey" FOREIGN KEY ("moduleId") REFERENCES "TB_MODULE"("_id") ON DELETE CASCADE ON UPDATE CASCADE;
