-- CreateTable
CREATE TABLE "TB_CLIENT_HISTORY" (
    "_id" TEXT NOT NULL,
    "observation" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3),
    "deletedAt" TIMESTAMPTZ(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "StatusEnum" NOT NULL DEFAULT 'ACTIVE',
    "clientId" TEXT NOT NULL,

    CONSTRAINT "TB_CLIENT_HISTORY_pkey" PRIMARY KEY ("_id")
);

-- AddForeignKey
ALTER TABLE "TB_CLIENT_HISTORY" ADD CONSTRAINT "TB_CLIENT_HISTORY_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "TB_CLIENT"("_id") ON DELETE RESTRICT ON UPDATE CASCADE;
