-- DropForeignKey
ALTER TABLE "TB_COST_CENTER" DROP CONSTRAINT "TB_COST_CENTER_clientId_fkey";

-- AlterTable
ALTER TABLE "TB_COST_CENTER" ALTER COLUMN "clientId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "TB_COST_CENTER" ADD CONSTRAINT "TB_COST_CENTER_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "TB_CLIENT"("_id") ON DELETE SET NULL ON UPDATE CASCADE;
