version: '3.8'

services:
  test-db:
    image: postgres:15.4-alpine
    container_name: pg_test_container
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_test
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s

  mongo:
    image: mongo
    container_name: mongodb_test_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
    ports:
    - "27017:27017"

  wait-for-postgres:
    image: dadarek/wait-for-dependencies
    environment:
      SLEEP_LENGTH: 3
      TIMEOUT_LENGTH: 10
    depends_on:
      - test-db
      - mongo