#
# Only for development
#

version: '3.8'

services:
  app:
    build: .
    container_name: dev
    env_file: .env
    
  db:
    image: postgres:15.4-alpine
    container_name: aginco_pg
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_dev
    ports:
      - '5432:5432'
    volumes:
      - aginco_data:/var/lib/postgresql/data

volumes:
  aginco_data: