#!/bin/bash

export AMBIENTE_NODE=$NODE_ENV
export NIVEL_LOG=$LOG_LEVEL
export PORTA_APLICACAO=$APP_PORT
export URL_BANCO_DADOS=$DATABASE_URL_DEV
export CHAVE_API_SENDGRID=$SENDGRID_API_KEY
export SEGREDO_AT=$AT_SECRET
export SEGREDO_RT=$RT_SECRET
export EMAIL_SECRET_TK=$TK_EMAIL_SECRET
export EMAIL_TK_TEMPODEVIDA=$TK_EMAIL_LIFETIME
export ENDERECO_FRONTEND=$FRONT_END_URL_DEV
export URL_API_GOOGLE=$GOOGLE_API_URL
export CHAVE_API_GOOGLE=$GOOGLE_API_KEY
export URI_MONGODB=$MONGODB_URI_DEV
export LOGIN_MULTIPLO=$MULTIPLE_LOGIN
export DESATIVAR_IPS_REQUERIDOS=$DEACTIVATE_REQUIRED_IPS_IN_REQUEST
export TEMPO_VIDA_ACESSO_JWT=$JWT_ACCESS_LIFETIME
export TEMPO_VIDA_REFRESH_JWT=$JWT_REFRESH_LIFETIME
export EMAIL_ORIGEM=$EMAIL_OPTIONS_FROM
export URL_RECUPERACAO_SENHA_FRONTEND=$FRONTEND_RECOVER_PASSWORD_URL_DEV
export ID_POOL_IDENTIDADE_AWS=$AWS_IDENTITY_POOL_ID
export REGIAO_BUCKET_AWS=$AWS_BUCKET_REGION
export REGIAO=$AWS_DEFAULT_REGION
export IMAGEM_DO_CONTAINER=$FULL_IMAGE_NAME
export FAMILIA="TASK-DEFINITION-$AMBIENTE"
export AMBIENTE=$AMBIENTE
export ROLE=$ROLE
export ECS_CPU=$ecs_cpu_dev
export ECS_MEMORIA=$ecs_memory_dev
export NOME_DO_CONTAINER=$container_name
export NOME_DO_SERVICO_CONTAINER=$container_service_name
export NOME_BUCKET_PUBLICO_AWS=$AWS_PUBLIC_BUCKET_NAME_DEV
export ID_CHAVE_ACESSO_AWS=$AWS_ACCESS_KEY_ID
export SEGREDO_CHAVE_ACESSO_AWS=$AWS_SECRET_ACCESS_KEY

# Escape function to handle special characters for sed
escape_sed() {
    echo "$1" | sed -e 's/[\/&]/\\&/g'
}

# List of keys that correspond to environment variables
KEYS=(
    "AMBIENTE_NODE"
    "NIVEL_LOG"
    "PORTA_APLICACAO"
    "URL_BANCO_DADOS"
    "CHAVE_API_SENDGRID"
    "SEGREDO_AT"
    "SEGREDO_RT"
    "EMAIL_SECRET_TK"
    "EMAIL_TK_TEMPODEVIDA"
    "ENDERECO_BACKEND"
    "ENDERECO_FRONTEND"
    "AMBIENTE"
    "URL_API_GOOGLE"
    "CHAVE_API_GOOGLE"
    "URI_MONGODB"
    "LOGIN_MULTIPLO"
    "DESATIVAR_IPS_REQUERIDOS"
    "SEGREDO_JWT_ZENDESK"
    "CHAVE_KID_ZENDESK"
    "BUCKET_ARQUIVOS_TEMPORARIOS"
    "TEMPO_VIDA_ACESSO_JWT"
    "TEMPO_VIDA_REFRESH_JWT"
    "EMAIL_ORIGEM"
    "URL_RECUPERACAO_SENHA_FRONTEND"
    "ID_POOL_IDENTIDADE_AWS"
    "REGIAO_BUCKET_AWS"
    "IMAGEM_DO_CONTAINER"
    "REGIAO"
    "FAMILIA"
    "ROLE"
    "ECS_CPU"
    "ECS_MEMORIA"
    "NOME_DO_CONTAINER"
    "NOME_DO_SERVICO_CONTAINER"
    "NOME_BUCKET_PUBLICO_AWS"
    "ID_CHAVE_ACESSO_AWS"
    "SEGREDO_CHAVE_ACESSO_AWS"
)

# Loop through the keys and replace each placeholder with its corresponding value
for KEY in "${KEYS[@]}"; do
    VALUE=$(escape_sed "${!KEY}")
    echo "Substituindo $KEY por $VALUE no $CONFIG_FILE"
    
    awk -v key="$KEY" -v value="$VALUE" '{ gsub(key, value); print }' $CONFIG_FILE > temp.tfvars && mv temp.tfvars $CONFIG_FILE
done
